"""add repository indexing metadata

Revision ID: 7ceb339366ab
Revises: ab8a569a568f
Create Date: 2026-08-29 14:53:08.578351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ceb339366ab'
down_revision: Union[str, Sequence[str], None] = 'ab8a569a568f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('repositories', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'error_message')
    op.drop_column('repositories', 'indexed_at')
    # ### end Alembic commands ###
