"""add repository status

Revision ID: ab8a569a568f
Revises: b9be62ee67a2
Create Date: 2026-08-29 08:58:12.493687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab8a569a568f'
down_revision: Union[str, Sequence[str], None] = 'b9be62ee67a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'repositories',
        sa.Column(
            'status',
            sa.String(length=30),
            nullable=True
        )
    )

    op.execute(
        "UPDATE repositories SET status = 'PENDING' WHERE status IS NULL"
    )

    op.alter_column(
        'repositories',
        'status',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'status')
    # ### end Alembic commands ###
